#!/bin/sh

set -eu

exec 2>&1

COMMAND=/usr/local/sbin/php-fpm

# Check nginx command is executable or not
test -x ${COMMAND} || (echo "${COMMAND} not exists" && exit 1)


# print the app version info
${COMMAND} -v

UMASK_SET=${UMASK_SET:-000}
# Allow groups to change files.
# umask 002

umask ${UMASK_SET}

# run the service
echo "service start: php-fpm"

# ${COMMAND} -F
/usr/local/bin/docker-php-entrypoint -F
